# filepath: /C:/Users/Administrator/Desktop/FaceSlider-MultiLang/.github/workflows/deplot-pages.yml
name: Deploy FaceSlider to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy FaceSlider.html to deployment folder
        run: |
          mkdir deployment
          cp FaceSlider.html deployment/

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: deployment
          clean: true
          # token: ${{ secrets.ACTIONS_DEPLOY_KEY }}