name: Deploy to tiaozhan Pages

on:
  workflow_run:
    workflows:
      - Merge HTML, CSS, and JS into FaceSlider.html
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy and rename FaceSlider.html
        run: |
          mkdir deployment
          cp merged/FaceSlider.html deployment/index.html

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: deployment
          clean: true