name: Merge HTML, CSS, and JS into deployment/index.html

on:
  push:
    paths:
      - 'html/**' # 仅当 html 文件夹下的文件发生更改时触发

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge HTML, CSS, and JS
        run: |
          mkdir -p deployment
          # 将 html/index.html 的内容写入 deployment/index.html
          cat html/index.html | sed '/<link.*style.css.*>/d' | sed '/<script.*script.js.*>/d' > deployment/index.html
          # 动态插入 CSS
          sed -i '/<\/head>/i <style>' deployment/index.html
          sed -i "/<\/head>/i $(cat html/style.css)" deployment/index.html
          sed -i '/<\/head>/i </style>' deployment/index.html
          # 动态插入 JS
          sed -i '/<\/body>/i <script>' deployment/index.html
          sed -i "/<\/body>/i $(cat html/script.js)" deployment/index.html
          sed -i '/<\/body>/i </script>' deployment/index.html

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: deployment
          clean: true